### ISSUE TITLE
CopyWebpackPlugin Configuration issues

### ISSUE THREAD

**Issue by AlexzPurewoko** [dicodingacademy/a163-bfwd-labs#3]
CopyWebpackPlugin now has new configuration, **patterns**. Please change to the new configuration because these old configuration makes error in webpack
```
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:                                                                        
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)                                                        
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.                                                                                                                           
    at validate (/home/apwdevs/Review/ReviewBFWD/Reserved_node_modules/node_modules/schema-utils/dist/validate.js:88:11)        
    at new CopyPlugin (/home/apwdevs/Review/ReviewBFWD/Reserved_node_modules/node_modules/copy-webpack-plugin/dist/index.js:24:30)                                                                                                                              
    at Object.<anonymous> (/home/apwdevs/Review/ReviewBFWD/javascriptsubs - Copy (2)/webpack.prod.js:25:5)                      
    at Module._compile (/home/apwdevs/Review/ReviewBFWD/Reserved_node_modules/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)                                                                                                
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)                                                   
    at Module.load (internal/modules/cjs/loader.js:977:32)                                                                      
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)                                                            
    at Module.require (internal/modules/cjs/loader.js:1019:19)                                                                  
    at require (/home/apwdevs/Review/ReviewBFWD/Reserved_node_modules/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)   
```                              

New Configuration
![dewreg](https://user-images.githubusercontent.com/17692360/82949997-c5de9700-9fce-11ea-85de-fea1e037d3e8.png)

**Comment by dimasmds** [comment]
Thanks, Updated!
